#===============================================================================
# UTC4 - MODULO 1: CALCULO DE PUNTAJES
# Calcula: Puntaje ISOES, Puntaje Descuento, Puntaje Global
#===============================================================================
# Para el calculo, se restringe las IES FESNA Y CUN según alcance de la Gerencia de Posmedia (rad. 3-2026-5931)
LISTADO_OFERTA_PROPUESTA<- LISTADO_OFERTA_PROPUESTA[!LISTADO_OFERTA_PROPUESTA$CODIGO_INSTITUCION %in% c(4719,4813),]

#===============================================================================
# CALCULAR PUNTAJE ISOES
#===============================================================================
LISTADO_OFERTA_PROPUESTA <- LISTADO_OFERTA_PROPUESTA %>%  mutate(ISOES_MIN = min(ISOES_PROGRAMA), ISOES_MAX = max(ISOES_PROGRAMA))
LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_ISOES <- 25 * ((LISTADO_OFERTA_PROPUESTA$ISOES_PROGRAMA - LISTADO_OFERTA_PROPUESTA$ISOES_MIN)/(LISTADO_OFERTA_PROPUESTA$ISOES_MAX-LISTADO_OFERTA_PROPUESTA$ISOES_MIN))

View(LISTADO_OFERTA_PROPUESTA[,c("CODIGO_INSTITUCION","CODIGO_SNIES_DEL_PROGRAMA","ISOES_PROGRAMA","ISOES_MIN","ISOES_MAX","TOTAL_PUNTAJE_ISOES")])

#===============================================================================
# CALCULAR PUNTAJE DESCUENTO
#===============================================================================
# Para el cálculo del puntaje, el descuento adicional se trunca a un máximo de 15% según alcance de la Gerencia de Posmedia (rad. 3-2026-5773); el valor original se mantiene para efectos económicos
LISTADO_OFERTA_PROPUESTA[LISTADO_OFERTA_PROPUESTA$`%_ADICIONAL`> 0.15,"%_ADICIONAL"] <- 0.15
LISTADO_OFERTA_PROPUESTA <- LISTADO_OFERTA_PROPUESTA %>%  mutate(DESCUENTO_ADICIONAL_MIN = min(`%_ADICIONAL`), DESCUENTO_ADICIONAL_MAX = max(`%_ADICIONAL`))
LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_DESCUENTO <- 30 * ((LISTADO_OFERTA_PROPUESTA$`%_ADICIONAL`  - LISTADO_OFERTA_PROPUESTA$DESCUENTO_ADICIONAL_MIN)/(LISTADO_OFERTA_PROPUESTA$DESCUENTO_ADICIONAL_MAX-LISTADO_OFERTA_PROPUESTA$DESCUENTO_ADICIONAL_MIN))

View(LISTADO_OFERTA_PROPUESTA[,c("CODIGO_INSTITUCION","CODIGO_SNIES_DEL_PROGRAMA","%_ADICIONAL","DESCUENTO_ADICIONAL_MIN","DESCUENTO_ADICIONAL_MAX","TOTAL_PUNTAJE_DESCUENTO")])

#===============================================================================
# SUMATORIA CRITERIOS PARA PUNTAJE_GLOBAL
#===============================================================================
LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_FIJO <- as.double(LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_FIJO)
LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_ISOES <- as.double(LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_ISOES)
LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_DESCUENTO <- as.double(LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_DESCUENTO)

LISTADO_OFERTA_PROPUESTA$PUNTAJE_GLOBAL <- LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_FIJO + LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_ISOES + LISTADO_OFERTA_PROPUESTA$TOTAL_PUNTAJE_DESCUENTO
