#===============================================================================
# UTC4 - MODULO 3: ASIGNACION DE CUPOS Y PRESUPUESTO
# Motor iterativo: Momento 1 y Momento 2
#===============================================================================

#===============================================================================
# PRESUPUESTO
#===============================================================================

PPTO_INICIAL <- c(5410442689)
PRESUPUESTO <- as.data.frame(PPTO_INICIAL)
ORDENAMIENTO_PROG$CUPO_ASIGNADO_MOMENTO1 <- 0
ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_MOMENTO1 <- 0

#-------------------------------------------------------------------------------
# CALCULO DE CUPOS
# MOMENTO 1
#-------------------------------------------------------------------------------

PRESUPUESTO$PPTO_MOMENTO1 <- PRESUPUESTO$PPTO_INICIAL


for (ID_PROGRAMA in ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA){
  print(paste(" ORDEN_PROG_",ID_PROGRAMA))
  EVALUAR_PROG <- ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA==ID_PROGRAMA,]

  #SE CREAN VARIABLES DE CALCULO DE CUPOS
  CUPO_OFERTADO <- EVALUAR_PROG$`#_ESTUDIANTES`
  CUPO_CALCULADO <- PRESUPUESTO$PPTO_MOMENTO1/EVALUAR_PROG$VALOR_ESTUDIANTE_ATENEA
  TOTAL_COHORTE <- EVALUAR_PROG$VALOR_ESTUDIANTE_ATENEA

  #------------------------------------------
  # REGLA_1 CUPO_CALCULADO es mayor a CUPO_OFERTADO
  #------------------------------------------
  if(as.integer(CUPO_CALCULADO) >= CUPO_OFERTADO){
    print("REGLA_1 SE ASIGNA CUPO OFERTADO")
    ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA== ID_PROGRAMA, "CUPO_ASIGNADO_MOMENTO1"] <- CUPO_OFERTADO
    #COSTO A RESTAR EN EL PRESUPUESTO DE LA IES
    COSTO_CUPOS <- CUPO_OFERTADO * TOTAL_COHORTE
    ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA== ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_MOMENTO1"] <- COSTO_CUPOS

    #RESTAR VALOR EN PRESUPUESTO
    PRESUPUESTO$PPTO_MOMENTO1 <- PRESUPUESTO$PPTO_MOMENTO1 - COSTO_CUPOS
  }
  else
    if(as.integer(CUPO_CALCULADO) >=100){
      print("REGLA_2 SE ASIGNA CUPO CALCULADO")
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA== ID_PROGRAMA, "CUPO_ASIGNADO_MOMENTO1"] <- as.integer(CUPO_CALCULADO)
      #COSTO A RESTAR EN EL PRESUPUESTO DE LA IES
      COSTO_CUPOS <- as.integer(CUPO_CALCULADO) * TOTAL_COHORTE
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA== ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_MOMENTO1"] <- COSTO_CUPOS

      #RESTAR VALOR EN PRESUPUESTO
      PRESUPUESTO$PPTO_MOMENTO1 <- PRESUPUESTO$PPTO_MOMENTO1 - COSTO_CUPOS
    }
  else{
      print( paste("UTC4_LLAVE_OFERTA",ID_PROGRAMA, "NO FINANCIA MINIMO DE CUPOS, CUPOS QUE SE PUEDEN FINANCIAR",as.integer(CUPO_CALCULADO), sep = " ") )
    }

} # CIERRE RECORRIDOS PROGRAMA

sum(ORDENAMIENTO_PROG$CUPO_ASIGNADO_MOMENTO1)
sum(ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_MOMENTO1)

#-------------------------------------------------------------------------------
# CALCULO DE CUPOS
# MOMENTO 2
#-------------------------------------------------------------------------------

ORDENAMIENTO_PROG$CUPO_ASIGNADO_MOMENTO2 <- 0
ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_MOMENTO2 <- 0

PRESUPUESTO$PPTO_MOMENTO2 <- PRESUPUESTO$PPTO_MOMENTO1

PROG_MOMENTO2 <- ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$CUPO_ASIGNADO_MOMENTO1 > 0,]
PROG_MOMENTO2 <- PROG_MOMENTO2[order(PROG_MOMENTO2$UTC4_LLAVE_OFERTA),]

for (ID_PROGRAMA in PROG_MOMENTO2$UTC4_LLAVE_OFERTA){
  print(paste(" ORDEN_PROG_",ID_PROGRAMA))
  EVALUAR_PROG <- PROG_MOMENTO2[PROG_MOMENTO2$UTC4_LLAVE_OFERTA==ID_PROGRAMA,]

  #SE CREAN VARIABLES DE CALCULO DE CUPOS
  CUPO_OFERTADO <- EVALUAR_PROG$CUPOS_MOMENTO_2
  CUPO_CALCULADO <- PRESUPUESTO$PPTO_MOMENTO2/EVALUAR_PROG$VALOR_ESTUDIANTE_ATENEA
  TOTAL_COHORTE <- EVALUAR_PROG$VALOR_ESTUDIANTE_ATENEA

  #------------------------------------------
  # REGLA_1 CUPO_CALCULADO es mayor a CUPO_OFERTADO
  #------------------------------------------
  if(as.integer(CUPO_CALCULADO) >= CUPO_OFERTADO){
    print("REGLA_1 SE ASIGNA CUPO OFERTADO")
    ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA== ID_PROGRAMA, "CUPO_ASIGNADO_MOMENTO2"] <- CUPO_OFERTADO
    #COSTO A RESTAR EN EL PRESUPUESTO DE LA IES
    COSTO_CUPOS <- CUPO_OFERTADO * TOTAL_COHORTE
    ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA== ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_MOMENTO2"] <- COSTO_CUPOS

    #RESTAR VALOR EN PRESUPUESTO
    PRESUPUESTO$PPTO_MOMENTO2 <- PRESUPUESTO$PPTO_MOMENTO2 - COSTO_CUPOS
  }
  else
    if(as.integer(CUPO_CALCULADO) > 0){
      print("REGLA_2 SE ASIGNA CUPO CALCULADO")
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA== ID_PROGRAMA, "CUPO_ASIGNADO_MOMENTO2"] <- as.integer(CUPO_CALCULADO)
      #COSTO A RESTAR EN EL PRESUPUESTO DE LA IES
      COSTO_CUPOS <- as.integer(CUPO_CALCULADO) * TOTAL_COHORTE
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$UTC4_LLAVE_OFERTA== ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_MOMENTO2"] <- COSTO_CUPOS

      #RESTAR VALOR EN PRESUPUESTO
      PRESUPUESTO$PPTO_MOMENTO2 <- PRESUPUESTO$PPTO_MOMENTO2 - COSTO_CUPOS
    }
  else{
    print( paste("UTC4_LLAVE_OFERTA",ID_PROGRAMA, "NO FINANCIA MINIMO DE CUPOS, CUPOS QUE SE PUEDEN FINANCIAR",as.integer(CUPO_CALCULADO), sep = " ") )
  }

} # CIERRE RECORRIDOS PROGRAMA

sum(ORDENAMIENTO_PROG$CUPO_ASIGNADO_MOMENTO2)
sum(ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_MOMENTO2)

#--------------------------------------------
# CALCULO CUPOS ASIGNADOS TOTALES
#--------------------------------------------
ORDENAMIENTO_PROG$CUPO_ASIGNADO_TOTAL <- ORDENAMIENTO_PROG$CUPO_ASIGNADO_MOMENTO1 + ORDENAMIENTO_PROG$CUPO_ASIGNADO_MOMENTO2
ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADOS_TOTAL <- ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_MOMENTO1 + ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_MOMENTO2

sum(ORDENAMIENTO_PROG$CUPO_ASIGNADO_TOTAL)
sum(ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADOS_TOTAL) + sum(PRESUPUESTO$PPTO_MOMENTO2)
PPTO_INICIAL
